In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv(r"C:\\Users\moses\Downloads\emails.csv")

In [3]:
pd.set_option('display.max_columns', None)
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  in  on  is  this  \
0   Email 1    0   0    1    0    0   0    2    0    0   0   0   1     0   
1   Email 2    8  13   24    6    6   2  102    1   27  18  21  13     0   
2   Email 3    0   0    1    0    0   0    8    0    0   4   2   0     0   
3   Email 4    0   5   22    0    5   1   51    2   10   1   5   9     2   
4   Email 5    7   6   17    1    5   2   57    0    9   3  12   2     2   

   enron   i  be  that  will  have  with  your  at  we   s  are  it  by  com  \
0      0   2   0     0     0     0     0     0   0   0   3    0   0   0    0   
1      1  61   4     2     0     0     2     0  12   9  95    4   3   3    3   
2      0   8   0     0     0     0     0     0   2   0   2    0   0   0    0   
3      0  16   2     0     0     1     1     0   2   1  36    3   1   2    0   
4      0  30   8     0     0     2     0     0   7   0  19    2   4   2    0   

   as  from  gas  or  not  me  deal  if  meter  hpl  please  re    e  any  \
0   1     0    0   0    0   0     0   0      0    0       0   2    4    0   
1  12     3    1  21    1  12     0   1      0    0       2  15  141    0   
2   2     0    2   0    0   0     0   0      0    0       0   0    3    0   
3   2     3    0  10    2   5     2   0      1    0       0  10   79    0   
4   4     1    2   6    0   6     0   0      3    0       1  10   71    0   

   our  corp  can   d  all  has  was  know  need  an  forwarded  new   t  may  \
0    0     0    0   0    0    0    0     0     0   0          0    0   4    0   
1   21     1    1  39    1    0    0     0     0  14          3    0  91    0   
2    0     0    0   3    0    0    0     0     0   0          0    0   3    0   
3    0     0    1  21    0    2    0     0     0   3          2    0  49    0   
4    0     0    1  11    8    0    1     0     0   9          2    0  63    0   

   up  j  mmbtu  should  do  am  get  out  see  no  there  price  daren  but  \
0   0  1      0       0   0   0    0    0    0   0      0      0      0    0   
1   2  8      0       0   0   7    2    1    1   5      0      0      3    0   
2   0  1      0       0   1   0    0    0    0   2      0      0      0    0   
3   0  5      0       0   1   9    0    0    1   3      0      0      2    0   
4   0  3      0       1   0   1    1    0    0   9      3      0      1    0   

   been  company   l  these  let  so  would   m  into  xls  farmer  attached  \
0     0        0   0      0    0   0      0   2     0    0       0         0   
1     0        0  35      0    0   7      1  46     0    0       3         1   
2     0        0   4      0    0   0      0   2     0    0       0         0   
3     1        0  27      0    0   1      0  24     0    0       1         0   
4     1        0  34      1    0   0      0  30     0    0       0         0   

   us  information  they  message  day  time  my  one  what  only  http  th  \
0   0            0     0        0    0     0   0    0     0     0     0   0   
1   2            0     0        0    2     2   1    3     0     0     0  15   
2   0            0     0        0    0     0   0    0     0     0     0   0   
3   0            0     0        0    1     0   0    1     0     0     0   4   
4   0            0     0        0    0     0   0    0     0     0     0  12   

   volume  mail  contract  which  month  more  robert  sitara  about  texas  \
0       0     0         0      0      0     0       0       0      0      0   
1       0     1         0      0      0     0       0       0      1      0   
2       0     0         0      0      0     0       0       0      0      0   
3       1     0         0      0      0     0       0       0      0      0   
4       3     0         4      0      0     0       0       0      0      0   

   nom  energy  pec  questions  www  deals  volumes  pm  ena  now  their  \
0    0       0    0          0    0      0        0   0    0    0      0   
1    2       0    2          0    0      0        

In [4]:
data.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [4]:
X = data.iloc[:,1:3001]
X

the  to  ect  and  for  of    a  you  hou  in  on  is  this  enron   i  \
0       0   0    1    0    0   0    2    0    0   0   0   1     0      0   2   
1       8  13   24    6    6   2  102    1   27  18  21  13     0      1  61   
2       0   0    1    0    0   0    8    0    0   4   2   0     0      0   8   
3       0   5   22    0    5   1   51    2   10   1   5   9     2      0  16   
4       7   6   17    1    5   2   57    0    9   3  12   2     2      0  30   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ..  ..   ...    ...  ..   
5167    2   2    2    3    0   0   32    0    0   5   6   1     0      0  20   
5168   35  27   11    2    6   5  151    4    3  23  18   6     3      1  98   
5169    0   0    1    1    0   0   11    0    0   1   1   3     1      0  10   
5170    2   7    1    0    2   1   28    2    0   8  11   7     1      0  39   
5171   22  24    5    1    6   5  148    8    2  23  13   5     4      1  99   

      be  that  will  have  with  your  at  we    s  are  it  by  com  as  \
0      0     0     0     0     0     0   0   0    3    0   0   0    0   1   
1      4     2     0     0     2     0  12   9   95    4   3   3    3  12   
2      0     0     0     0     0     0   2   0    2    0   0   0    0   2   
3      2     0     0     1     1     0   2   1   36    3   1   2    0   2   
4      8     0     0     2     0     0   7   0   19    2   4   2    0   4   
...   ..   ...   ...   ...   ...   ...  ..  ..  ...  ...  ..  ..  ...  ..   
5167   1     0     0     1     0     0   3   0   18    1   5   0    0   2   
5168  10     6     2     2     6     1  11  15  101    2  12   1    3  25   
5169   0     0     0     0     0     0   1   0   11    0   1   0    0   1   
5170   1     0     0     0     2     1   3   3   37    0   8   0    4   5   
5171   6     4     1     1     1     1   6  16   89    4   5   0    1  22   

      from  gas  or  not  me  deal  if  meter  hpl  please  re    e  any  our  \
0        0    0   0    0   0     0   0      0    0       0   2    4    0    0   
1        3    1  21    1  12     0   1      0    0       2  15  141    0   21   
2        0    2   0    0   0     0   0      0    0       0   0    3    0    0   
3        3    0  10    2   5     2   0      1    0       0  10   79    0    0   
4        1    2   6    0   6     0   0      3    0       1  10   71    0    0   
...    ...  ...  ..  ...  ..   ...  ..    ...  ...     ...  ..  ...  ...  ...   
5167     2    0   1    0   3     0   0      0    0       0   5   29    0    1   
5168     3    5  14    7  14     0   3      0    0       1  17  218    3    2   
5169     0    0   1    0   2     0   0      0    0       0   0   12    0    0   
5170     1    0   5    0   3     1   1      0    0       1   3   45    0    2   
5171     5    5  16    7  18     0   1      0    0       1  14  191    2    2   

      corp  can   d  all  has  was  know  need  an  forwarded  new    t  may  \
0        0    0   0    0    0    0     0     0   0          0    0    4    0   
1        1    1  39    1    0    0     0     0  14          3    0   91    0   
2        0    0   3    0    0    0     0     0   0          0    0    3    0   
3        0    1  21    0    2    0     0     0   3          2    0   49    0   
4        0    1  11    8    0    1     0     0   9          2    0   63    0   
...    ...  ...  ..  ...  ...  ...   ...   ...  ..        ...  ...  ...  ...   
5167     0    0  14    0    0    0     0     0  10          0    0   30    0   
5168     0    4  56    3    4    1     1     2  25          0    0  190    0   
5169     0    0   2    0    0    0     0     0   2          0    0   11    0   
5170     0    1   9    0    0    0     0     1   3          0    0   50    0   
5171     0    3  54    6    2    1     1     2  21          0    0  154    0   

      up   j  mmbtu  should  do  am  get  out  see  no  there  price  daren  \
0      0   1      0       0   0   0    0    0    0   0      0      0      0   
1      2   8      0       0 

In [6]:
Y = data.iloc[:,-1].values
Y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [14]:
yhat = LR.predict(X_test)
yhat

array([1, 0, 0, ..., 1, 1, 0], dtype=int64)

In [15]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[2.88188510e-01, 7.11811490e-01],
       [9.48493159e-01, 5.15068410e-02],
       [9.94632891e-01, 5.36710883e-03],
       ...,
       [2.05142814e-09, 9.99999998e-01],
       [4.44769455e-02, 9.55523054e-01],
       [9.99986989e-01, 1.30107879e-05]])